## Investigasi sampel data titanic berikut dengan cara :
1. Cek secara head, tail, sample, info lalu observasi apa yang bisa anda peroleh ?
2. Lakukan Statistical Summary dengan mengekstrak informasi yang didapat dari observasi anda ?
3. Cek apakah ada duplikat dan bagaimana handlenya ?
4. Cek apakah ada missing value, berapa persentasenya jika ada, dan bagaimana cara handlenya ?

# Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

# Load Data

In [ ]:
# import data
df = pd.read_excel('titanic.xlsx')
data = df.copy()

#  Preliminary

In [ ]:
data.head()

   survived                                             name     sex      age
0         1                    Allen, Miss. Elisabeth Walton  female  29.0000
1         1                   Allison, Master. Hudson Trevor    male   0.9167
2         0                     Allison, Miss. Helen Loraine  female   2.0000
3         0             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

In [ ]:
data.tail()

     survived                                     name     sex   age
495         1  Mallet, Mrs. Albert (Antoinette Magnin)  female  24.0
496         0        Mangiavacchi, Mr. Serafino Emilio    male   NaN
497         0               Matthews, Mr. William John    male  30.0
498         0                Maybery, Mr. Frank Hubert    male  40.0
499         0                McCrae, Mr. Arthur Gordon    male  32.0

In [ ]:
data.sample(5)

,survived,name,sex,age
452,0,"Hold, Mr. Stephen",male,44.0000
99,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0000
438,1,"Herman, Miss. Alice",female,24.0000
277,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN
1,1,"Allison, Master. Hudson Trevor",male,0.9167

Observation:
1. Columns `name` and `sex` are categorical, columns `survived` and `age` are numeric.
2. `sex` column seems to contain two distinct values (male OR female), but will confirm later
3. `survived` is apparently also binary (0,1)
4. No obvious defect on the data (column name vs its entries), all looks good

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  500 non-null    int64
 1   name      500 non-null    object
 2   sex       500 non-null    object
 3   age       451 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 15.8+ KB

Observation:
1. Data contains 4 columns with 500 rows
2. Only the age column has missing values, it will be handled later
3. All dtypes seem OK (appropriate), given the corresponding column name

# Statistical Summary

In [ ]:
data.columns

Index(['survived', 'name', 'sex', 'age'], dtype='object')

In [ ]:
# group column names based on type
categoricals = ['name', 'sex']

numericals = ['survived', 'age']

In [ ]:
data[numericals].describe()

         survived         age
count  500.000000  451.000000
mean     0.540000   35.917775
std      0.498897   14.766454
min      0.000000    0.666700
25%      0.000000   24.000000
50%      1.000000   35.000000
75%      1.000000   47.000000
max      1.000000   80.000000

Observations:

*   Overall, the minimum and maximum values make sense for each column
*   Mean ~50% (Median) in the `age` column indicates a somewhat symmetrical distribution
*   `survived` column is boolean/binary column since the value is 0 or 1, no need to conclude its simmetricity. Only need to check balance level

In [ ]:
data[categoricals].describe()

                                  name   sex
count                              500   500
unique                             499     2
top     Eustis, Miss. Elizabeth Mussey  male
freq                                 2   288

Observations:
* `sex` has 2 unique values, 'male' OR 'female'
* The most passengers' gender is male (288 rows), the rest are female.
* in the `name` column there are 2 data that have the same name (Eustis, Miss. Elizabeth Mussey), it is necessary to check further whether the data is duplicate data.

In [ ]:
for col in categoricals:
  print(f"Value counts of {col} column")
  print(data[col].value_counts(), '\n')

Value counts of name column
name
Eustis, Miss. Elizabeth Mussey                                                        2
Becker, Miss. Ruth Elizabeth                                                          1
Becker, Miss. Marion Louise                                                           1
Becker, Master. Richard F                                                             1
Beauchamp, Mr. Henry James                                                            1
Beane, Mrs. Edward (Ethel Clarke)                                                     1
Beane, Mr. Edward                                                                     1
Bateman, Rev. Robert James                                                            1
Banfield, Mr. Frederick James                                                         1
Ball, Mrs. (Ada E Hall)                                                               1
Baimbrigge, Mr. Charles Robert                                                        1
Bailey, Mr. Percy Andrew                                                              1
Ashby, Mr. John                                                                       1
Angle, Mrs. William A (Florence "Mary" Agnes Hughes)                                  1
Becker, Mrs. Allen Oliver (Nellie E Baumgardner)                                      1
Andrew, Mr. Frank Thomas                                                              1
Andrew, Mr. Edgardo Samuel                                                            1
Aldworth, Mr. Charles Augustus                                                        1
Abelson, Mrs. Samuel (Hannah Wizosky)                                                 1
Abelson, Mr. Samuel                                                                   1
Young, Miss. Marie Grice                                                              1
Wright, Mr. George                                                                    1
Woolner, Mr. Hugh                                                                     1
Wilson, Miss. Helen Alice                                                             1
Williams-Lambert, Mr. Fletcher Fellows                                                1
Williams, Mr. Richard Norris II                                                       1
Williams, Mr. Charles Duane                                                           1
Willard, Miss. Constance                                                              1
Widener, Mrs. George Dunton (Eleanor Elkins)                                          1
Widener, Mr. Harry Elkins                                                             1
Angle, Mr. William A                                                                  1
Clarke, Mr. Charles Valentine                                                         1
Christy, Mrs. (Alice Frances)                                                         1
Christy, Miss. Julie Rachel                                                           1
Chapman, Mrs. John Henry (Sara Elizabeth Lawry)                                       1
Chapman, Mr. John Henry                                                               1
Chapman, Mr. Charles Henry                                                            1
Carter, Rev. Ernest Courtenay                                                         1
Carter, Mrs. Ernest Courtenay (Lilian Hughes)                                         1
Carbines, Mr. William                                                                 1
Campbell, Mr. William                                                                 1
Cameron, Miss. Clear Annie                                                            1
Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)                                   1
Caldwell, Mr. Albert Francis                                                          1
Caldwell, Master. Alden Gates                                                         1
Beesley, Mr. Lawrence                                                                 1
Byles, Rev. Thomas Roussel Davids                                                     1
Butler, Mr. Reginald Fenton                                                           1
Buss, Miss. Kate                                                                      1
Bryhl, Mr. Kurt Arnold Gottfrid                                                       1
Bryhl, Miss. Dagmar Jenny Ingeborg                                                    1
Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)                         1
Brown, Mr. Thomas William Solomon                                                     1
Brown, Miss. Edith Eileen                                                             1
Brown, Miss. Amelia "Mildred"                                                         1
Bracken, Mr. James H                                                                  1
Bowenur, Mr. Solomon                                                                  1
Botsford, Mr. William Hull                                                            1
Berriman, Mr. William John                                                            1
Bentham, Miss. Lilian W                                                               1
Clarke, Mrs. Charles V (Ada Maria Winfield)                                           1
Bystrom, Mrs. (Karolina)                                                              1
Stead, Mr. William Thomas                                                             1
Stahelin-Maeglin, Dr. Max                                                             1
Spencer, Mrs. William Augustus (Marie Eugenie)                                        1
Spencer, Mr. William Augustus                                                         1
Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)                              1
Spedden, Mr. Frederic Oakley                                                          1
Spedden, Master. Robert Douglas                                                       1
Snyder, Mrs. John Pillsbury (Nelle Stevenson)                                         1
Snyder, Mr. John Pillsbury                                                            1
Smith, Mrs. Lucien Philip (Mary Eloise Hughes)                                        1
Smith, Mr. Richard William                                                            1
Smith, Mr. Lucien Philip                                                              1
Smith, Mr. James Clinch                                                               1
Smart, Mr. John Montgomery                                                            1
Widener, Mr. George Dunton                                                            1
Simonius-Blumer, Col. Oberst Alfons                                                   1
Silvey, Mrs. William Baird (Alice Munger)                                             1
Silvey, Mr. William Baird                                                             1
Silverthorne, Mr. Spencer Victor                                                      1
Shutes, Miss. Elizabeth W                                                             1
Seward, Mr. Frederic Kimber                                                           1
Serepeca, Miss. Augusta                                                               1
Schabert, Mrs. Paul (Emma Mock)                                                       1
Salomon, Mr. Abraham L                                                                1
Sagesser, Mlle. Emma                                                                  1
Saalfeld, Mr. Adolphe                                                                 1
Ryerson, Mrs. Arthur Larned (Emily Maria Borie)                                       1
Ryerson, Mr. Arthur Larned                                                            1
Ryerson, Miss. Susan Parker "Suzette"                                                 1
Ryerson, Miss. Emily Borie                                                            1
Sloper, Mr. William Thompson                                                          1
Wick, Mrs. George Dennick (Mary Hitchcock)                                            1
Wick, Mr. George Dennick                                                              1
Wick, Miss. Mary Natalie                                                              1
White, Mrs. John Stuart (Ella Holmes)                                                 1
White, Mr. Richard Frasar                                                             1
White, Mr. Percival Wayland                                                           1
Weir, Col. John                                                                       1
Warren, Mrs. Frank Manley (Anna Sophia Atkinson)                                      1
Warren, Mr. Frank Manley                                                              1
Ward, Miss. Anna                                                                      1
Walker, Mr. William Anderson                                                          1
Van der hoef, Mr. Wyckoff                                                             1
Uruchurtu, Don. Manuel E                                                              1
Tucker, Mr. Gilbert Milligan Jr                                                       1
Thorne, Mrs. Gertrude Maybelle                                                        1
Stengel, Mr. Charles Emil Henry                                                       1
Thayer, Mr. John Borland Jr                                                           1
Thayer, Mr. John Borland                                                              1
Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)                                     1
Taylor, Mr. Elmer Zebley                                                              1
Taussig, Mrs. Emil (Tillie Mandelbaum)                                                1
Taussig, Mr. Emil                                                                     1
Taussig, Miss. Ruth                                                                   1
Swift, Mrs. Frederick Joel (Margaret Welles Barron)                                   1
Sutton, Mr. Frederick                                                                 1
Straus, Mrs. Isidor (Rosalie Ida Blun)                                                1
Straus, Mr. Isidor                                                                    1
Stone, Mrs. George Nelson (Martha Evelyn)                                             1
Stewart, Mr. Albert A                                                                 1
Stephenson, Mrs. Walter Bertram (Martha Eustis)                                       1
Stengel, Mrs. Charles Emil Henry (Annie May Morris)                                   1
Thayer, Mrs. John Borland (Marian Longstreth Morris)                                  1
Kantor, Mr. Sinai                                                                     1
Jerwan, Mrs. Amin S (Marie Marthe Thuillard)                                          1
Jenkin, Mr. Stephen Curnow                                                            1
Jefferys, Mr. Ernest Wilfred                                                          1
Jefferys, Mr. Clifford Thomas                                                         1
Jarvis, Mr. John Denzil                                                               1
Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)                                   1
Jacobsohn, Mr. Sidney Samuel                                                          1
Ilett, Miss. Bertha                                                                   1
Hunt, Mr. George Henry                                                                1
Howard, Mrs. Benjamin (Ellen Truelove Arman)                                          1
Howard, Mr. Benjamin                                                                  1
Hosono, Mr. Masabumi                                                                  1
Hood, Mr. Ambrose Jr                                                                  1
Coleridge, Mr. Reginald Charles                                                       1
Hold, Mr. Stephen                                                                     1
Hodges, Mr. Henry Price                                                               1
Hocking, Mrs. Elizabeth (Eliza Needs)                                                 1
Hocking, Mr. Samuel James Metcalfe                                                    1
Hocking, Mr. Richard George                                                           1
Hocking, Miss. Ellen "Nellie"                                                         1
Hiltunen, Miss. Marta                                                                 1
Hickman, Mr. Stanley George                                                           1
Hickman, Mr. Lewis                                                                    1
Hickman, Mr. Leonard Mark                                                             1
Hewlett, Mrs. (Mary D Kingcome)                                                       1
Herman, Mrs. Samuel (Jane Laver)                                                      1
Herman, Mr. Samuel                                                                    1
Herman, Miss. Kate                                                                    1
Herman, Miss. Alice                                                                   1
Hold, Mrs. Stephen (Annie Margaret Hill)                                              1
Baxter, Mrs. James (Helene DeLaudeniere Chaput)                                       1
Baxter, Mr. Quigg Edmond                                                              1
Baumann, Mr. John D                                                                   1
Barkworth, Mr. Algernon Henry Wilson                                                  1
Barber, Miss. Ellen "Nellie"                                                          1
Aubart, Mme. Leontine Pauline                                                         1
Astor, Mrs. John Jacob (Madeleine Talmadge Force)                                     1
Astor, Col. John Jacob                                                                1
Artagaveytia, Mr. Ramon                                                               1
Appleton, Mrs. Edward Dale (Charlotte Lamson)                                         1
Andrews, Mr. Thomas Jr                                                                1
Andrews, Miss. Kornelia Theodosia                                                     1
Anderson, Mr. Harry                                                                   1
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)                                       1
Leitch, Miss. Jessie Wills                                                            1
McCrae, Mr. Arthur Gordon                                                             1
Maybery, Mr. Frank Hubert                                                             1
Matthews, Mr. William John                                                            1
Mangiavacchi, Mr. Serafino Emilio                                                     1
Mallet, Mrs. Albert (Antoinette Magnin)                                               1
Mallet, Mr. Albert                                                                    1
Mallet, Master. Andre                                                                 1
Malachard, Mr. Noel                                                                   1
Mack, Mrs. (Mary)                                                                     1
Louch, Mrs. Charles Alexander (Alice Adelaide Slow)                                   1
Louch, Mr. Charles Alexander                                                          1
Lingane, Mr. John                                                                     1
Leyson, Mr. Robert William Norman                                                     1
Levy, Mr. Rene Jacques                                                                1
Lemore, Mrs. (Amelia Milley)                                                          1
Allison, Mr. Hudson Joshua Creighton                                                  1
Eitemiller, Mr. George Floyd                                                          1
Duran y More, Miss. Florentina                                                        1
Duran y More, Miss. Asuncion                                                          1
Drew, Mrs. James Vivian (Lulu Thorne Christian)                                       1
Drew, Mr. James Vivian                                                                1
Drew, Master. Marshall Brines                                                         1
Downton, Mr. William James                                                            1
Doling, Mrs. John T (Ada Julia Bone)                                                  1
Doling, Miss. Elsie                                                                   1
Dibden, Mr. William                                                                   1
Denbury, Mr. Herbert                                                                  1
del Carlo, Mrs. Sebastiano (Argenia Genovesi)                                         1
del Carlo, Mr. Sebastiano                                                             1
Deacon, Mr. Percy William                                                             1
Hart, Mrs. Benjamin (Esther Ada Bloomfield)                                           1
Davis, Miss. Mary                                                                     1
Davies, Mrs. John Morgan (Elizabeth Agnes Mary White)                                 1
Davies, Mr. Charles Henry                                                             1
Davies, Master. John Morgan Jr                                                        1
Cunningham, Mr. Alfred Fleming                                                        1
Cotterill, Mr. Henry "Harry"                                                          1
Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)                                   1
Corbett, Mrs. Walter H (Irene Colvin)                                                 1
Cook, Mrs. (Selena Rogers)                                                            1
Collyer, Mrs. Harvey (Charlotte Annie Tate)                                           1
Collyer, Mr. Harvey                                                                   1
Collyer, Miss. Marjorie "Lottie"                                                      1
Collett, Mr. Sidney C Stuart                                                          1
Collander, Mr. Erik Gustaf                                                            1
Allison, Master. Hudson Trevor                                                        1
de Brito, Mr. Jose Joaquim                                                            1
Hart, Mr. Benjamin                                                                    1
Hart, Miss. Eva Miriam                                                                1
Harris, Mr. Walter                                                                    1
Harris, Mr. George                                                                    1
Harper, Rev. John                                                                     1
Harper, Miss. Annie Jessie "Nina"                                                     1
Harbeck, Mr. William H                                                                1
Hamalainen, Mrs. William (Anna)                                                       1

In [ ]:
for col in numericals:
  print(f"==== {col} ====")
  print(data[col].value_counts(), '\n')

==== survived ====
survived
1    270
0    230
Name: count, dtype: int64

==== age ====
age
24.0000    23
30.0000    20
36.0000    19
18.0000    14
42.0000    14
45.0000    14
35.0000    14
22.0000    12
28.0000    12
23.0000    11
21.0000    11
31.0000    11
48.0000    11
25.0000    11
29.0000    10
54.0000    10
50.0000    10
34.0000    10
47.0000    10
39.0000     9
27.0000     9
33.0000     8
49.0000     8
38.0000     8
19.0000     8
40.0000     8
55.0000     8
32.0000     7
60.0000     7
17.0000     7
26.0000     7
44.0000     6
52.0000     6
37.0000     6
58.0000     6
64.0000     5
46.0000     5
57.0000     5
51.0000     5
16.0000     4
53.0000     4
56.0000     4
43.0000     4
62.0000     4
61.0000     4
1.0000      3
8.0000      3
63.0000     3
41.0000     3
15.0000     2
71.0000     2
20.0000     2
65.0000     2
4.0000      2
6.0000      2
2.0000      1
0.9167      1
14.0000     1
11.0000     1
76.0000     1
59.0000     1
80.0000     1
28.5000     1
32.5000     1
70.0000     1
45.5000     1
13.0000     1
67.0000     1
12.0000     1
0.8333      1
0.6667      1
7.0000      1
3.0000      1
Name: count, dtype: int64

# Cleaning Data

## 1. Duplicate Handling

In [ ]:
len(data)

500

In [ ]:
len(data.drop_duplicates())

499

In [ ]:
len(data.drop_duplicates()) / len(data)
#if the output of the code in this cell is not 1 then there are duplicates

0.998

In [ ]:
# Step 1: Get duplicate rows (including the original one)
duplicates = data[data.duplicated(keep=False)]

In [ ]:
duplicates

     survived                            name     sex   age
104         1  Eustis, Miss. Elizabeth Mussey  female  54.0
349         1  Eustis, Miss. Elizabeth Mussey  female  54.0

In [ ]:
duplicates.groupby(list(data.columns)).size().reset_index(name = 'duplicate_count')

   survived                            name     sex   age  duplicate_count
0         1  Eustis, Miss. Elizabeth Mussey  female  54.0                2

it is verified a row that has the same name (Eustis, Miss. Elizabeth Mussey) is duplicate

In [ ]:
#Handling Drop duplicate
data = data.drop_duplicates()

In [ ]:
len(data.drop_duplicates()) / len(data)
#if the output of the code in this cell is not 1 then there are duplicates

1.0

### Has handled duplicate drops

## 2. Missing value handling
### Identifying Missing value

In [ ]:
data.isna().sum()

survived     0
name         0
sex          0
age         49
dtype: int64

missing values only in `age` column

In [ ]:
for column in data.columns:
    print(f"============= {column} =================")
    display(data[column].value_counts())
    print()

============= survived =================

survived
1    269
0    230
Name: count, dtype: int64

============= name =================

name
McCrae, Mr. Arthur Gordon                                                             1
Allen, Miss. Elisabeth Walton                                                         1
Allison, Master. Hudson Trevor                                                        1
Lehmann, Miss. Bertha                                                                 1
Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)                                 1
Laroche, Mr. Joseph Philippe Lemercier                                                1
Laroche, Miss. Simonne Marie Anne Andree                                              1
Laroche, Miss. Louise                                                                 1
Lamb, Mr. John Joseph                                                                 1
Lahtinen, Rev. William                                                                1
Lahtinen, Mrs. William (Anna Sylfven)                                                 1
Kvillner, Mr. Johan Henrik Johannesson                                                1
Knight, Mr. Robert J                                                                  1
Kirkland, Rev. Charles Leonard                                                        1
Kelly, Mrs. Florence "Fannie"                                                         1
Keane, Mr. Daniel                                                                     1
Keane, Miss. Nora A                                                                   1
Karnes, Mrs. J Frank (Claire Bennett)                                                 1
Kantor, Mrs. Sinai (Miriam Sternin)                                                   1
Borebank, Mr. John James                                                              1
Bonnell, Miss. Elizabeth                                                              1
Bonnell, Miss. Caroline                                                               1
Blank, Mr. Henry                                                                      1
Blackwell, Mr. Stephen Weart                                                          1
Bjornstrom-Steffansson, Mr. Mauritz Hakan                                             1
Bissette, Miss. Amelia                                                                1
Bishop, Mrs. Dickinson H (Helen Walton)                                               1
Bishop, Mr. Dickinson H                                                               1
Birnbaum, Mr. Jakob                                                                   1
Bird, Miss. Ellen                                                                     1
Bidois, Miss. Rosalie                                                                 1
Behr, Mr. Karl Howell                                                                 1
Beckwith, Mrs. Richard Leonard (Sallie Monypeny)                                      1
Beckwith, Mr. Richard Leonard                                                         1
Beattie, Mr. Thomson                                                                  1
Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)                       1
Cardeza, Mr. Thomas Drake Martinez                                                    1
Candee, Mrs. Edward (Helen Churchill Hungerford)                                      1
Calderhead, Mr. Edward Pennington                                                     1
Cairns, Mr. Alexander                                                                 1
Butt, Major. Archibald Willingham                                                     1
Burns, Miss. Elizabeth Margaret                                                       1
Bucknell, Mrs. William Robert (Emma Eliza Ward)                                       1
Brown, Mrs. John Murray (Caroline Lane Lamson)                                        1
Brown, Mrs. James Joseph (Margaret Tobin)                                             1
Brewe, Dr. Arthur Jackson                                                             1
Brandeis, Mr. Emil                                                                    1
Brady, Mr. John Bertram                                                               1
Bradley, Mr. George ("George Arthur Brayton")                                         1
Bowerman, Miss. Elsie Edith                                                           1
Bowen, Miss. Grace Scott                                                              1
Chaudanson, Miss. Victorine                                                           1
Chambers, Mrs. Norman Campbell (Bertha Griggs)                                        1
Chambers, Mr. Norman Campbell                                                         1
Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)                               1
Chaffee, Mr. Herbert Fuller                                                           1
Cavendish, Mrs. Tyrell William (Julia Florence Siegel)                                1
Cavendish, Mr. Tyrell William                                                         1
Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)                           1
Case, Mr. Howard Brown                                                                1
Carter, Mrs. William Ernest (Lucile Polk)                                             1
Carter, Mr. William Ernest                                                            1
Carter, Miss. Lucile Polk                                                             1
Carter, Master. William Thornton II                                                   1
Carrau, Mr. Jose Pedro                                                                1
Carrau, Mr. Francisco M                                                               1
Carlsson, Mr. Frans Olof                                                              1
Crosby, Miss. Harriet R                                                               1
Crosby, Capt. Edward Gifford                                                          1
Crafton, Mr. John Bertram                                                             1
Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)                                  1
Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)                                 1
Compton, Mr. Alexander Taylor Jr                                                      1
Compton, Miss. Sara Rebecca                                                           1
Colley, Mr. Edward Pomeroy                                                            1
Clifford, Mr. George Quincy                                                           1
Cleaver, Miss. Alice                                                                  1
Clark, Mrs. Walter Miller (Virginia McDowell)                                         1
Clark, Mr. Walter Miller                                                              1
Chisholm, Mr. Roderick Robert Crispin                                                 1
Chibnall, Mrs. (Edith Martha Bowerman)                                                1
Chevre, Mr. Paul Romaine                                                              1
Cherry, Miss. Gladys                                                                  1
Douglas, Mrs. Walter Donald (Mahala Dutton)                                           1
Douglas, Mrs. Frederick Charles (Mary Helene Baxter)                                  1
Douglas, Mr. Walter Donald                                                            1
Dodge, Mrs. Washington (Ruth Vidaver)                                                 1
Dodge, Master. Washington                                                             1
Dodge, Dr. Washington                                                                 1
Dick, Mrs. Albert Adrian (Vera Gillespie)                                             1
Dick, Mr. Albert Adrian                                                               1
Davidson, Mrs. Thornton (Orian Hays)                                                  1
Davidson, Mr. Thornton                                                                1
Daniels, Miss. Sarah                                                                  1
Daniel, Mr. Robert Williams                                                           1
Daly, Mr. Peter Denis                                                                 1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)                                   1
Cumings, Mr. John Bradley                                                             1
Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)                            1
Fortune, Mr. Charles Alexander                                                        1
Fortune, Miss. Mabel Helen                                                            1
Fortune, Miss. Ethel Flora                                                            1
Fortune, Miss. Alice Elizabeth                                                        1
Foreman, Mr. Benjamin Laventall                                                       1
Flynn, Mr. John Irwin ("Irving")                                                      1
Fleming, Miss. Margaret                                                               1
Flegenheim, Mrs. Alfred (Antoinette)                                                  1
Farthing, Mr. John                                                                    1
Evans, Miss. Edith Corse                                                              1
Eustis, Miss. Elizabeth Mussey                                                        1
Endres, Miss. Caroline Louise                                                         1
Earnshaw, Mrs. Boulton (Olive Potter)                                                 1
Dulles, Mr. William Crothers                                                          1
Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")                                          1
Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")                     1
Gibson, Miss. Dorothy Winifred                                                        1
Geiger, Miss. Amalie                                                                  1
Gee, Mr. Arthur H                                                                     1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                                          1
Futrelle, Mr. Jacques Heath                                                           1
Fry, Mr. Richard                                                                      1
Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)                       1
Frolicher-Stehli, Mr. Maxmillian                                                      1
Frolicher, Miss. Hedwig Margaritha                                                    1
Frauenthal, Mrs. Henry William (Clara Heinsheimer)                                    1
Frauenthal, Mr. Isaac Gerald                                                          1
Frauenthal, Dr. Henry William                                                         1
Franklin, Mr. Thomas Parham                                                           1
Francatelli, Miss. Laura Mabel                                                        1
Fortune, Mrs. Mark (Mary McDougald)                                                   1
Fortune, Mr. Mark                                                                     1
Harper, Mrs. Henry Sleeper (Myna Haxtun)                                              1
Harper, Mr. Henry Sleeper                                                             1
Harder, Mrs. George Achilles (Dorothy Annan)                                          1
Harder, Mr. George Achilles                                                           1
Guggenheim, Mr. Benjamin                                                              1
Greenfield, Mrs. Leo David (Blanche Strouse)                                          1
Greenfield, Mr. William Bertram                                                       1
Graham, Mrs. William Thompson (Edith Junkins)                                         1
Graham, Mr. George Edward                                                             1
Graham, Miss. Margaret Edith                                                          1
Gracie, Col. Archibald IV                                                             1
Goldschmidt, Mr. George B                                                             1
Goldenberg, Mrs. Samuel L (Edwiga Grabowska)                                          1
Goldenberg, Mr. Samuel L                                                              1
Giglio, Mr. Victor                                                                    1
Gibson, Mrs. Leonard (Pauline C Boeson)                                               1
Holverson, Mr. Alexander Oskar                                                        1
Hogeboom, Mrs. John C (Anna Andrews)                                                  1
Hippach, Mrs. Louis Albert (Ida Sophia Fischer)                                       1
Hippach, Miss. Jean Gertrude                                                          1
Hipkins, Mr. William Edward                                                           1
Hilliard, Mr. Herbert Henry                                                           1
Head, Mr. Christopher                                                                 1
Hays, Mrs. Charles Melville (Clara Jennings Gregg)                                    1
Hays, Mr. Charles Melville                                                            1
Hays, Miss. Margaret Bechstein                                                        1
Hawksford, Mr. Walter James                                                           1
Hassab, Mr. Hammad                                                                    1
Harrison, Mr. William                                                                 1
Harris, Mrs. Henry Birkhardt (Irene Wallach)                                          1
Harris, Mr. Henry Birkhardt                                                           1
Harrington, Mr. Charles H                                                             1
Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)                                      1
Kimball, Mr. Edwin Nelson Jr                                                          1
Kenyon, Mrs. Frederick R (Marion)                                                     1
Kenyon, Mr. Frederick R                                                               1
Kent, Mr. Edward Austin                                                               1
Keeping, Mr. Edwin                                                                    1
Julian, Mr. Henry Forbes                                                              1
Jones, Mr. Charles Cresson                                                            1
Ismay, Mr. Joseph Bruce                                                               1
Isham, Miss. Ann Elizabeth                                                            1
Icard, Miss. Amelie                                                                   1
Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)                                       1
Hoyt, Mr. William Fisher                                                              1
Hoyt, Mr. Frederick Maxfield                                                          1
Homer, Mr. Harry ("Mr E Haven")                                                       1
Holverson, Mrs. Alexander Oskar (Mary Aline Towner)                                   1
Maguire, Mr. John Edward                                                              1
Madill, Miss. Georgette Alexandra                                                     1
Lurette, Miss. Elise                                                                  1
Loring, Mr. Joseph Holland                                                            1
Longley, Miss. Gretchen Fiske                                                         1
Long, Mr. Milton Clyde                                                                1
Lines, Mrs. Ernest H (Elizabeth Lindsey James)                                        1
Lines, Miss. Mary Conover                                                             1
Lindstrom, Mrs. Carl Johan (Sigrid Posse)                                             1
Lindeberg-Lind, Mr. Erik Gustaf ("Mr Edward Lingrey")                                 1
Lewy, Mr. Ervin G                                                                     1
Lesurer, Mr. Gustave J                                                                1
LeRoy, Miss. Bertha                                                                   1
Leader, Dr. Alice (Farnham)                                                           1
Kreuchen, Miss. Emilie                                                                1
Klaber, Mr. Herman                                                                    1
Molson, Mr. Harry Markland                                                            1
Mock, Mr. Philipp Edmund                                                              1
Minahan, Mrs. William Edward (Lillian E Thorpe)                                       1
Minahan, Miss. Daisy E                                                                1
Minahan, Dr. William Edward                                                           1
Millet, Mr. Francis Davis                                                             1
Meyer, Mrs. Edgar Joseph (Leila Saks)                                                 1
Meyer, Mr. Edgar Joseph                                                               1
McGough, Mr. James Robert                                                             1
McCarthy, Mr. Timothy J                                                               1
McCaffry, Mr. Thomas Francis                                                          1
Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")                                      1
Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)                        1
Marvin, Mr. Daniel Warner                                                             1
Marechal, Mr. Pierre                                                                  1
Maioni, Miss. Roberta                                                                 1
Pears, Mr. Thomas Clinton                                                             1
Payne, Mr. Vivian Ponsonby                                                            1
Partner, Mr. Austen                                                                   1
Parr, Mr. William Henry Marsh                                                         1
Ovies y Rodriguez, Mr. Servando                                                       1
Ostby, Mr. Engelhart Cornelius                                                        1
Ostby, Miss. Helene Ragnhild                                                          1
Omont, Mr. Alfred Fernand                                                             1
Oliva y Ocana, Dona. Fermina                                                          1
Nicholson, Mr. Arthur Ernest                                                          1
Newsom, Miss. Helen Monypeny                                                          1
Newell, Mr. Arthur Webster                                                            1
Newell, Miss. Marjorie                                                                1
Newell, Miss. Madeleine                                                               1
Natsch, Mr. Charles H                                                                 1
Moore, Mr. Clarence Bloomfield                                                        1

============= sex =================

sex
male      288
female    211
Name: count, dtype: int64

============= age =================

age
24.0000    23
30.0000    20
36.0000    19
18.0000    14
42.0000    14
45.0000    14
35.0000    14
22.0000    12
28.0000    12
23.0000    11
21.0000    11
31.0000    11
48.0000    11
25.0000    11
29.0000    10
34.0000    10
50.0000    10
47.0000    10
39.0000     9
27.0000     9
54.0000     9
33.0000     8
49.0000     8
38.0000     8
19.0000     8
40.0000     8
55.0000     8
32.0000     7
60.0000     7
17.0000     7
26.0000     7
44.0000     6
52.0000     6
37.0000     6
58.0000     6
64.0000     5
46.0000     5
57.0000     5
51.0000     5
16.0000     4
53.0000     4
56.0000     4
43.0000     4
62.0000     4
61.0000     4
1.0000      3
8.0000      3
63.0000     3
41.0000     3
15.0000     2
71.0000     2
20.0000     2
65.0000     2
4.0000      2
6.0000      2
2.0000      1
0.9167      1
14.0000     1
11.0000     1
76.0000     1
59.0000     1
80.0000     1
28.5000     1
32.5000     1
70.0000     1
45.5000     1
13.0000     1
67.0000     1
12.0000     1
0.8333      1
0.6667      1
7.0000      1
3.0000      1
Name: count, dtype: int64

In [ ]:
total_rows = len(data)
total_rows

499

In [ ]:
# Calculate and display the percentage of missing values in each column one by one
for column in data.columns:
  missing_count = data[column].isna().sum()
  missing_percentage = (missing_count / total_rows) * 100
  print(f"Column '{column}' has {missing_count} missing values ({missing_percentage:.2f}%)")

Column 'survived' has 0 missing values (0.00%)
Column 'name' has 0 missing values (0.00%)
Column 'sex' has 0 missing values (0.00%)
Column 'age' has 49 missing values (9.82%)

The percentage of missing values below 20% so we handle numerically with median, categorical with mode. But the categorical data type does not have missing values.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 499 entries, 0 to 499
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  499 non-null    int64
 1   name      499 non-null    object
 2   sex       499 non-null    object
 3   age       450 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 19.5+ KB

In [ ]:
data['age'].median()

35.0

In [ ]:
data.isna().sum()

survived    0
name        0
sex         0
age         0
dtype: int64

Success removing NULL values!